#!/usr/bin/env python3
"""
Filename: fix_add_features_to_560_sets.py
Author(s): Kristophor Jensen
Date Created: 20251104_000000
Date Revised: 20251104_000000
File version: 1.0.0.1
Description: Fix empty feature sets by adding features using correct syntax

This script queries the database for all exp42 feature sets with 0 features,
determines which features should be in each set based on the naming convention,
and generates correct add-features-to-set commands using feature set IDs.

Usage:
  python3 fix_add_features_to_560_sets.py > fix_feature_sets.sh

Then in MLDP CLI:
  source fix_feature_sets.sh
"""

import psycopg2
import sys
import re

# Configuration
DB_HOST = 'localhost'
DB_NAME = 'arc_detection'
DB_USER = 'kjensen'
CATEGORY = 'exp42_separability'

# Feature name to ID mapping
FEATURE_MAP = {
    'vuhsnr': 95,   # v_ultra_high_snr
    'vuhpsd': 96,   # v_ultra_high_mean_psd
    'vuhslp': 97,   # v_ultra_high_slope
    'vuhsfm': 98,   # v_ultra_high_sfm
    'cuhsnr': 99,   # c_ultra_high_snr
    'cuhpsd': 100,  # c_ultra_high_mean_psd
    'cuhslp': 101,  # c_ultra_high_slope
    'cuhsfm': 102,  # c_ultra_high_sfm
    'vfsnr': 103,   # v_full_snr
    'vfpsd': 104,   # v_full_mean_psd
    'vfslp': 105,   # v_full_slope
    'vfsfm': 106,   # v_full_sfm
    'cfsnr': 107,   # c_full_snr
    'cfpsd': 108,   # c_full_mean_psd
    'cfslp': 109,   # c_full_slope
    'cfsfm': 110,   # c_full_sfm
}

def parse_feature_ids_from_name(fs_name):
    """Extract feature IDs from feature set name.

    Example: vuhsnr_vuhpsd_vuhslp_fs42 -> [95, 96, 97]
    """
    # Remove _fs42 suffix
    name = fs_name.replace('_fs42', '')

    # Split by underscore
    parts = name.split('_')

    # Map to feature IDs
    feature_ids = []
    for part in parts:
        if part in FEATURE_MAP:
            feature_ids.append(FEATURE_MAP[part])
        else:
            print(f"WARNING: Unknown feature abbreviation: {part}", file=sys.stderr)

    return sorted(feature_ids)

def main():
    """Query database and generate fix commands."""

    # Connect to database
    try:
        conn = psycopg2.connect(
            host=DB_HOST,
            database=DB_NAME,
            user=DB_USER
        )
        cursor = conn.cursor()
    except Exception as e:
        print(f"ERROR: Database connection failed: {e}", file=sys.stderr)
        sys.exit(1)

    # Query all exp42 feature sets
    try:
        cursor.execute("""
            SELECT fs.feature_set_id, fs.feature_set_name, COUNT(f.feature_id) as feature_count
            FROM ml_feature_sets_lut fs
            LEFT JOIN ml_feature_set_features f ON fs.feature_set_id = f.feature_set_id
            WHERE fs.category = %s
            GROUP BY fs.feature_set_id, fs.feature_set_name
            HAVING COUNT(f.feature_id) = 0
            ORDER BY fs.feature_set_id
        """, (CATEGORY,))

        empty_sets = cursor.fetchall()

    except Exception as e:
        print(f"ERROR: Database query failed: {e}", file=sys.stderr)
        sys.exit(1)
    finally:
        cursor.close()
        conn.close()

    total = len(empty_sets)
    print(f"# Found {total} feature sets with 0 features", file=sys.stderr)

    if total == 0:
        print("# No empty feature sets found. All sets already have features.", file=sys.stderr)
        sys.exit(0)

    # Generate fix commands
    print("# Fix Script: Add Features to Empty Feature Sets")
    print(f"# Generated by: fix_add_features_to_560_sets.py v1.0.0.1")
    print(f"# Empty sets found: {total}")
    print()
    print("# ============================================================================")
    print("# Add Features to Feature Sets")
    print("# ============================================================================")
    print()

    for idx, (fs_id, fs_name, feature_count) in enumerate(empty_sets, 1):
        # Parse feature IDs from name
        feature_ids = parse_feature_ids_from_name(fs_name)

        if len(feature_ids) != 3:
            print(f"# WARNING: Feature set {fs_id} ({fs_name}) has {len(feature_ids)} features, expected 3", file=sys.stderr)

        feature_list = " ".join(str(fid) for fid in feature_ids)

        print(f"# Feature Set {idx}/{total}: {fs_name} (ID: {fs_id})")
        print(f"add-features-to-set {fs_id} --features {feature_list}")
        print()

        # Progress markers every 50
        if idx % 50 == 0:
            print(f"# Progress: {idx}/{total} feature sets fixed ({idx*100//total}%)")
            print()

    print("# ============================================================================")
    print("# Fix Complete")
    print("# ============================================================================")
    print(f"# Total: {total} feature sets fixed")
    print()

    # Verification command
    print("# Verify all sets have 3 features:")
    print("# (SQL query to check feature counts)")
    print()

    print(f"\n# Summary:", file=sys.stderr)
    print(f"# - Empty feature sets found: {total}", file=sys.stderr)
    print(f"# - Commands generated: {total}", file=sys.stderr)

if __name__ == "__main__":
    main()
