# Found 560 feature sets with 0 features
# Fix Script: Add Features to Empty Feature Sets
# Generated by: fix_add_features_to_560_sets.py v1.0.0.1
# Empty sets found: 560

# ============================================================================
# Add Features to Feature Sets
# ============================================================================

# Feature Set 1/560: vuhsnr_vuhpsd_vuhslp_fs42 (ID: 25)
add-features-to-set 25 --features 95 96 97

# Feature Set 2/560: vuhsnr_vuhpsd_vuhsfm_fs42 (ID: 26)
add-features-to-set 26 --features 95 96 98

# Feature Set 3/560: vuhsnr_vuhpsd_cuhsnr_fs42 (ID: 27)
add-features-to-set 27 --features 95 96 99

# Feature Set 4/560: vuhsnr_vuhpsd_cuhpsd_fs42 (ID: 28)
add-features-to-set 28 --features 95 96 100

# Feature Set 5/560: vuhsnr_vuhpsd_cuhslp_fs42 (ID: 29)
add-features-to-set 29 --features 95 96 101

# Feature Set 6/560: vuhsnr_vuhpsd_cuhsfm_fs42 (ID: 30)
add-features-to-set 30 --features 95 96 102

# Feature Set 7/560: vuhsnr_vuhpsd_vfsnr_fs42 (ID: 31)
add-features-to-set 31 --features 95 96 103

# Feature Set 8/560: vuhsnr_vuhpsd_vfpsd_fs42 (ID: 32)
add-features-to-set 32 --features 95 96 104

# Feature Set 9/560: vuhsnr_vuhpsd_vfslp_fs42 (ID: 33)
add-features-to-set 33 --features 95 96 105

# Feature Set 10/560: vuhsnr_vuhpsd_vfsfm_fs42 (ID: 34)
add-features-to-set 34 --features 95 96 106

# Feature Set 11/560: vuhsnr_vuhpsd_cfsnr_fs42 (ID: 35)
add-features-to-set 35 --features 95 96 107

# Feature Set 12/560: vuhsnr_vuhpsd_cfpsd_fs42 (ID: 36)
add-features-to-set 36 --features 95 96 108

# Feature Set 13/560: vuhsnr_vuhpsd_cfslp_fs42 (ID: 37)
add-features-to-set 37 --features 95 96 109

# Feature Set 14/560: vuhsnr_vuhpsd_cfsfm_fs42 (ID: 38)
add-features-to-set 38 --features 95 96 110

# Feature Set 15/560: vuhsnr_vuhslp_vuhsfm_fs42 (ID: 39)
add-features-to-set 39 --features 95 97 98

# Feature Set 16/560: vuhsnr_vuhslp_cuhsnr_fs42 (ID: 40)
add-features-to-set 40 --features 95 97 99

# Feature Set 17/560: vuhsnr_vuhslp_cuhpsd_fs42 (ID: 41)
add-features-to-set 41 --features 95 97 100

# Feature Set 18/560: vuhsnr_vuhslp_cuhslp_fs42 (ID: 42)
add-features-to-set 42 --features 95 97 101

# Feature Set 19/560: vuhsnr_vuhslp_cuhsfm_fs42 (ID: 43)
add-features-to-set 43 --features 95 97 102

# Feature Set 20/560: vuhsnr_vuhslp_vfsnr_fs42 (ID: 44)
add-features-to-set 44 --features 95 97 103

# Feature Set 21/560: vuhsnr_vuhslp_vfpsd_fs42 (ID: 45)
add-features-to-set 45 --features 95 97 104

# Feature Set 22/560: vuhsnr_vuhslp_vfslp_fs42 (ID: 46)
add-features-to-set 46 --features 95 97 105

# Feature Set 23/560: vuhsnr_vuhslp_vfsfm_fs42 (ID: 47)
add-features-to-set 47 --features 95 97 106

# Feature Set 24/560: vuhsnr_vuhslp_cfsnr_fs42 (ID: 48)
add-features-to-set 48 --features 95 97 107

# Feature Set 25/560: vuhsnr_vuhslp_cfpsd_fs42 (ID: 49)
add-features-to-set 49 --features 95 97 108

# Feature Set 26/560: vuhsnr_vuhslp_cfslp_fs42 (ID: 50)
add-features-to-set 50 --features 95 97 109

# Feature Set 27/560: vuhsnr_vuhslp_cfsfm_fs42 (ID: 51)
add-features-to-set 51 --features 95 97 110

# Feature Set 28/560: vuhsnr_vuhsfm_cuhsnr_fs42 (ID: 52)
add-features-to-set 52 --features 95 98 99

# Feature Set 29/560: vuhsnr_vuhsfm_cuhpsd_fs42 (ID: 53)
add-features-to-set 53 --features 95 98 100

# Feature Set 30/560: vuhsnr_vuhsfm_cuhslp_fs42 (ID: 54)
add-features-to-set 54 --features 95 98 101

# Feature Set 31/560: vuhsnr_vuhsfm_cuhsfm_fs42 (ID: 55)
add-features-to-set 55 --features 95 98 102

# Feature Set 32/560: vuhsnr_vuhsfm_vfsnr_fs42 (ID: 56)
add-features-to-set 56 --features 95 98 103

# Feature Set 33/560: vuhsnr_vuhsfm_vfpsd_fs42 (ID: 57)
add-features-to-set 57 --features 95 98 104

# Feature Set 34/560: vuhsnr_vuhsfm_vfslp_fs42 (ID: 58)
add-features-to-set 58 --features 95 98 105

# Feature Set 35/560: vuhsnr_vuhsfm_vfsfm_fs42 (ID: 59)
add-features-to-set 59 --features 95 98 106

# Feature Set 36/560: vuhsnr_vuhsfm_cfsnr_fs42 (ID: 60)
add-features-to-set 60 --features 95 98 107

# Feature Set 37/560: vuhsnr_vuhsfm_cfpsd_fs42 (ID: 61)
add-features-to-set 61 --features 95 98 108

# Feature Set 38/560: vuhsnr_vuhsfm_cfslp_fs42 (ID: 62)
add-features-to-set 62 --features 95 98 109

# Feature Set 39/560: vuhsnr_vuhsfm_cfsfm_fs42 (ID: 63)
add-features-to-set 63 --features 95 98 110

# Feature Set 40/560: vuhsnr_cuhsnr_cuhpsd_fs42 (ID: 64)
add-features-to-set 64 --features 95 99 100

# Feature Set 41/560: vuhsnr_cuhsnr_cuhslp_fs42 (ID: 65)
add-features-to-set 65 --features 95 99 101

# Feature Set 42/560: vuhsnr_cuhsnr_cuhsfm_fs42 (ID: 66)
add-features-to-set 66 --features 95 99 102

# Feature Set 43/560: vuhsnr_cuhsnr_vfsnr_fs42 (ID: 67)
add-features-to-set 67 --features 95 99 103

# Feature Set 44/560: vuhsnr_cuhsnr_vfpsd_fs42 (ID: 68)
add-features-to-set 68 --features 95 99 104

# Feature Set 45/560: vuhsnr_cuhsnr_vfslp_fs42 (ID: 69)
add-features-to-set 69 --features 95 99 105

# Feature Set 46/560: vuhsnr_cuhsnr_vfsfm_fs42 (ID: 70)
add-features-to-set 70 --features 95 99 106

# Feature Set 47/560: vuhsnr_cuhsnr_cfsnr_fs42 (ID: 71)
add-features-to-set 71 --features 95 99 107

# Feature Set 48/560: vuhsnr_cuhsnr_cfpsd_fs42 (ID: 72)
add-features-to-set 72 --features 95 99 108

# Feature Set 49/560: vuhsnr_cuhsnr_cfslp_fs42 (ID: 73)
add-features-to-set 73 --features 95 99 109

# Feature Set 50/560: vuhsnr_cuhsnr_cfsfm_fs42 (ID: 74)
add-features-to-set 74 --features 95 99 110

# Progress: 50/560 feature sets fixed (8%)

# Feature Set 51/560: vuhsnr_cuhpsd_cuhslp_fs42 (ID: 75)
add-features-to-set 75 --features 95 100 101

# Feature Set 52/560: vuhsnr_cuhpsd_cuhsfm_fs42 (ID: 76)
add-features-to-set 76 --features 95 100 102

# Feature Set 53/560: vuhsnr_cuhpsd_vfsnr_fs42 (ID: 77)
add-features-to-set 77 --features 95 100 103

# Feature Set 54/560: vuhsnr_cuhpsd_vfpsd_fs42 (ID: 78)
add-features-to-set 78 --features 95 100 104

# Feature Set 55/560: vuhsnr_cuhpsd_vfslp_fs42 (ID: 79)
add-features-to-set 79 --features 95 100 105

# Feature Set 56/560: vuhsnr_cuhpsd_vfsfm_fs42 (ID: 80)
add-features-to-set 80 --features 95 100 106

# Feature Set 57/560: vuhsnr_cuhpsd_cfsnr_fs42 (ID: 81)
add-features-to-set 81 --features 95 100 107

# Feature Set 58/560: vuhsnr_cuhpsd_cfpsd_fs42 (ID: 82)
add-features-to-set 82 --features 95 100 108

# Feature Set 59/560: vuhsnr_cuhpsd_cfslp_fs42 (ID: 83)
add-features-to-set 83 --features 95 100 109

# Feature Set 60/560: vuhsnr_cuhpsd_cfsfm_fs42 (ID: 84)
add-features-to-set 84 --features 95 100 110

# Feature Set 61/560: vuhsnr_cuhslp_cuhsfm_fs42 (ID: 85)
add-features-to-set 85 --features 95 101 102

# Feature Set 62/560: vuhsnr_cuhslp_vfsnr_fs42 (ID: 86)
add-features-to-set 86 --features 95 101 103

# Feature Set 63/560: vuhsnr_cuhslp_vfpsd_fs42 (ID: 87)
add-features-to-set 87 --features 95 101 104

# Feature Set 64/560: vuhsnr_cuhslp_vfslp_fs42 (ID: 88)
add-features-to-set 88 --features 95 101 105

# Feature Set 65/560: vuhsnr_cuhslp_vfsfm_fs42 (ID: 89)
add-features-to-set 89 --features 95 101 106

# Feature Set 66/560: vuhsnr_cuhslp_cfsnr_fs42 (ID: 90)
add-features-to-set 90 --features 95 101 107

# Feature Set 67/560: vuhsnr_cuhslp_cfpsd_fs42 (ID: 91)
add-features-to-set 91 --features 95 101 108

# Feature Set 68/560: vuhsnr_cuhslp_cfslp_fs42 (ID: 92)
add-features-to-set 92 --features 95 101 109

# Feature Set 69/560: vuhsnr_cuhslp_cfsfm_fs42 (ID: 93)
add-features-to-set 93 --features 95 101 110

# Feature Set 70/560: vuhsnr_cuhsfm_vfsnr_fs42 (ID: 94)
add-features-to-set 94 --features 95 102 103

# Feature Set 71/560: vuhsnr_cuhsfm_vfpsd_fs42 (ID: 95)
add-features-to-set 95 --features 95 102 104

# Feature Set 72/560: vuhsnr_cuhsfm_vfslp_fs42 (ID: 96)
add-features-to-set 96 --features 95 102 105

# Feature Set 73/560: vuhsnr_cuhsfm_vfsfm_fs42 (ID: 97)
add-features-to-set 97 --features 95 102 106

# Feature Set 74/560: vuhsnr_cuhsfm_cfsnr_fs42 (ID: 98)
add-features-to-set 98 --features 95 102 107

# Feature Set 75/560: vuhsnr_cuhsfm_cfpsd_fs42 (ID: 99)
add-features-to-set 99 --features 95 102 108

# Feature Set 76/560: vuhsnr_cuhsfm_cfslp_fs42 (ID: 100)
add-features-to-set 100 --features 95 102 109

# Feature Set 77/560: vuhsnr_cuhsfm_cfsfm_fs42 (ID: 101)
add-features-to-set 101 --features 95 102 110

# Feature Set 78/560: vuhsnr_vfsnr_vfpsd_fs42 (ID: 102)
add-features-to-set 102 --features 95 103 104

# Feature Set 79/560: vuhsnr_vfsnr_vfslp_fs42 (ID: 103)
add-features-to-set 103 --features 95 103 105

# Feature Set 80/560: vuhsnr_vfsnr_vfsfm_fs42 (ID: 104)
add-features-to-set 104 --features 95 103 106

# Feature Set 81/560: vuhsnr_vfsnr_cfsnr_fs42 (ID: 105)
add-features-to-set 105 --features 95 103 107

# Feature Set 82/560: vuhsnr_vfsnr_cfpsd_fs42 (ID: 106)
add-features-to-set 106 --features 95 103 108

# Feature Set 83/560: vuhsnr_vfsnr_cfslp_fs42 (ID: 107)
add-features-to-set 107 --features 95 103 109

# Feature Set 84/560: vuhsnr_vfsnr_cfsfm_fs42 (ID: 108)
add-features-to-set 108 --features 95 103 110

# Feature Set 85/560: vuhsnr_vfpsd_vfslp_fs42 (ID: 109)
add-features-to-set 109 --features 95 104 105

# Feature Set 86/560: vuhsnr_vfpsd_vfsfm_fs42 (ID: 110)
add-features-to-set 110 --features 95 104 106

# Feature Set 87/560: vuhsnr_vfpsd_cfsnr_fs42 (ID: 111)
add-features-to-set 111 --features 95 104 107

# Feature Set 88/560: vuhsnr_vfpsd_cfpsd_fs42 (ID: 112)
add-features-to-set 112 --features 95 104 108

# Feature Set 89/560: vuhsnr_vfpsd_cfslp_fs42 (ID: 113)
add-features-to-set 113 --features 95 104 109

# Feature Set 90/560: vuhsnr_vfpsd_cfsfm_fs42 (ID: 114)
add-features-to-set 114 --features 95 104 110

# Feature Set 91/560: vuhsnr_vfslp_vfsfm_fs42 (ID: 115)
add-features-to-set 115 --features 95 105 106

# Feature Set 92/560: vuhsnr_vfslp_cfsnr_fs42 (ID: 116)
add-features-to-set 116 --features 95 105 107

# Feature Set 93/560: vuhsnr_vfslp_cfpsd_fs42 (ID: 117)
add-features-to-set 117 --features 95 105 108

# Feature Set 94/560: vuhsnr_vfslp_cfslp_fs42 (ID: 118)
add-features-to-set 118 --features 95 105 109

# Feature Set 95/560: vuhsnr_vfslp_cfsfm_fs42 (ID: 119)
add-features-to-set 119 --features 95 105 110

# Feature Set 96/560: vuhsnr_vfsfm_cfsnr_fs42 (ID: 120)
add-features-to-set 120 --features 95 106 107

# Feature Set 97/560: vuhsnr_vfsfm_cfpsd_fs42 (ID: 121)
add-features-to-set 121 --features 95 106 108

# Feature Set 98/560: vuhsnr_vfsfm_cfslp_fs42 (ID: 122)
add-features-to-set 122 --features 95 106 109

# Feature Set 99/560: vuhsnr_vfsfm_cfsfm_fs42 (ID: 123)
add-features-to-set 123 --features 95 106 110

# Feature Set 100/560: vuhsnr_cfsnr_cfpsd_fs42 (ID: 124)
add-features-to-set 124 --features 95 107 108

# Progress: 100/560 feature sets fixed (17%)

# Feature Set 101/560: vuhsnr_cfsnr_cfslp_fs42 (ID: 125)
add-features-to-set 125 --features 95 107 109

# Feature Set 102/560: vuhsnr_cfsnr_cfsfm_fs42 (ID: 126)
add-features-to-set 126 --features 95 107 110

# Feature Set 103/560: vuhsnr_cfpsd_cfslp_fs42 (ID: 127)
add-features-to-set 127 --features 95 108 109

# Feature Set 104/560: vuhsnr_cfpsd_cfsfm_fs42 (ID: 128)
add-features-to-set 128 --features 95 108 110

# Feature Set 105/560: vuhsnr_cfslp_cfsfm_fs42 (ID: 129)
add-features-to-set 129 --features 95 109 110

# Feature Set 106/560: vuhpsd_vuhslp_vuhsfm_fs42 (ID: 130)
add-features-to-set 130 --features 96 97 98

# Feature Set 107/560: vuhpsd_vuhslp_cuhsnr_fs42 (ID: 131)
add-features-to-set 131 --features 96 97 99

# Feature Set 108/560: vuhpsd_vuhslp_cuhpsd_fs42 (ID: 132)
add-features-to-set 132 --features 96 97 100

# Feature Set 109/560: vuhpsd_vuhslp_cuhslp_fs42 (ID: 133)
add-features-to-set 133 --features 96 97 101

# Feature Set 110/560: vuhpsd_vuhslp_cuhsfm_fs42 (ID: 134)
add-features-to-set 134 --features 96 97 102

# Feature Set 111/560: vuhpsd_vuhslp_vfsnr_fs42 (ID: 135)
add-features-to-set 135 --features 96 97 103

# Feature Set 112/560: vuhpsd_vuhslp_vfpsd_fs42 (ID: 136)
add-features-to-set 136 --features 96 97 104

# Feature Set 113/560: vuhpsd_vuhslp_vfslp_fs42 (ID: 137)
add-features-to-set 137 --features 96 97 105

# Feature Set 114/560: vuhpsd_vuhslp_vfsfm_fs42 (ID: 138)
add-features-to-set 138 --features 96 97 106

# Feature Set 115/560: vuhpsd_vuhslp_cfsnr_fs42 (ID: 139)
add-features-to-set 139 --features 96 97 107

# Feature Set 116/560: vuhpsd_vuhslp_cfpsd_fs42 (ID: 140)
add-features-to-set 140 --features 96 97 108

# Feature Set 117/560: vuhpsd_vuhslp_cfslp_fs42 (ID: 141)
add-features-to-set 141 --features 96 97 109

# Feature Set 118/560: vuhpsd_vuhslp_cfsfm_fs42 (ID: 142)
add-features-to-set 142 --features 96 97 110

# Feature Set 119/560: vuhpsd_vuhsfm_cuhsnr_fs42 (ID: 143)
add-features-to-set 143 --features 96 98 99

# Feature Set 120/560: vuhpsd_vuhsfm_cuhpsd_fs42 (ID: 144)
add-features-to-set 144 --features 96 98 100

# Feature Set 121/560: vuhpsd_vuhsfm_cuhslp_fs42 (ID: 145)
add-features-to-set 145 --features 96 98 101

# Feature Set 122/560: vuhpsd_vuhsfm_cuhsfm_fs42 (ID: 146)
add-features-to-set 146 --features 96 98 102

# Feature Set 123/560: vuhpsd_vuhsfm_vfsnr_fs42 (ID: 147)
add-features-to-set 147 --features 96 98 103

# Feature Set 124/560: vuhpsd_vuhsfm_vfpsd_fs42 (ID: 148)
add-features-to-set 148 --features 96 98 104

# Feature Set 125/560: vuhpsd_vuhsfm_vfslp_fs42 (ID: 149)
add-features-to-set 149 --features 96 98 105

# Feature Set 126/560: vuhpsd_vuhsfm_vfsfm_fs42 (ID: 150)
add-features-to-set 150 --features 96 98 106

# Feature Set 127/560: vuhpsd_vuhsfm_cfsnr_fs42 (ID: 151)
add-features-to-set 151 --features 96 98 107

# Feature Set 128/560: vuhpsd_vuhsfm_cfpsd_fs42 (ID: 152)
add-features-to-set 152 --features 96 98 108

# Feature Set 129/560: vuhpsd_vuhsfm_cfslp_fs42 (ID: 153)
add-features-to-set 153 --features 96 98 109

# Feature Set 130/560: vuhpsd_vuhsfm_cfsfm_fs42 (ID: 154)
add-features-to-set 154 --features 96 98 110

# Feature Set 131/560: vuhpsd_cuhsnr_cuhpsd_fs42 (ID: 155)
add-features-to-set 155 --features 96 99 100

# Feature Set 132/560: vuhpsd_cuhsnr_cuhslp_fs42 (ID: 156)
add-features-to-set 156 --features 96 99 101

# Feature Set 133/560: vuhpsd_cuhsnr_cuhsfm_fs42 (ID: 157)
add-features-to-set 157 --features 96 99 102

# Feature Set 134/560: vuhpsd_cuhsnr_vfsnr_fs42 (ID: 158)
add-features-to-set 158 --features 96 99 103

# Feature Set 135/560: vuhpsd_cuhsnr_vfpsd_fs42 (ID: 159)
add-features-to-set 159 --features 96 99 104

# Feature Set 136/560: vuhpsd_cuhsnr_vfslp_fs42 (ID: 160)
add-features-to-set 160 --features 96 99 105

# Feature Set 137/560: vuhpsd_cuhsnr_vfsfm_fs42 (ID: 161)
add-features-to-set 161 --features 96 99 106

# Feature Set 138/560: vuhpsd_cuhsnr_cfsnr_fs42 (ID: 162)
add-features-to-set 162 --features 96 99 107

# Feature Set 139/560: vuhpsd_cuhsnr_cfpsd_fs42 (ID: 163)
add-features-to-set 163 --features 96 99 108

# Feature Set 140/560: vuhpsd_cuhsnr_cfslp_fs42 (ID: 164)
add-features-to-set 164 --features 96 99 109

# Feature Set 141/560: vuhpsd_cuhsnr_cfsfm_fs42 (ID: 165)
add-features-to-set 165 --features 96 99 110

# Feature Set 142/560: vuhpsd_cuhpsd_cuhslp_fs42 (ID: 166)
add-features-to-set 166 --features 96 100 101

# Feature Set 143/560: vuhpsd_cuhpsd_cuhsfm_fs42 (ID: 167)
add-features-to-set 167 --features 96 100 102

# Feature Set 144/560: vuhpsd_cuhpsd_vfsnr_fs42 (ID: 168)
add-features-to-set 168 --features 96 100 103

# Feature Set 145/560: vuhpsd_cuhpsd_vfpsd_fs42 (ID: 169)
add-features-to-set 169 --features 96 100 104

# Feature Set 146/560: vuhpsd_cuhpsd_vfslp_fs42 (ID: 170)
add-features-to-set 170 --features 96 100 105

# Feature Set 147/560: vuhpsd_cuhpsd_vfsfm_fs42 (ID: 171)
add-features-to-set 171 --features 96 100 106

# Feature Set 148/560: vuhpsd_cuhpsd_cfsnr_fs42 (ID: 172)
add-features-to-set 172 --features 96 100 107

# Feature Set 149/560: vuhpsd_cuhpsd_cfpsd_fs42 (ID: 173)
add-features-to-set 173 --features 96 100 108

# Feature Set 150/560: vuhpsd_cuhpsd_cfslp_fs42 (ID: 174)
add-features-to-set 174 --features 96 100 109

# Progress: 150/560 feature sets fixed (26%)

# Feature Set 151/560: vuhpsd_cuhpsd_cfsfm_fs42 (ID: 175)
add-features-to-set 175 --features 96 100 110

# Feature Set 152/560: vuhpsd_cuhslp_cuhsfm_fs42 (ID: 176)
add-features-to-set 176 --features 96 101 102

# Feature Set 153/560: vuhpsd_cuhslp_vfsnr_fs42 (ID: 177)
add-features-to-set 177 --features 96 101 103

# Feature Set 154/560: vuhpsd_cuhslp_vfpsd_fs42 (ID: 178)
add-features-to-set 178 --features 96 101 104

# Feature Set 155/560: vuhpsd_cuhslp_vfslp_fs42 (ID: 179)
add-features-to-set 179 --features 96 101 105

# Feature Set 156/560: vuhpsd_cuhslp_vfsfm_fs42 (ID: 180)
add-features-to-set 180 --features 96 101 106

# Feature Set 157/560: vuhpsd_cuhslp_cfsnr_fs42 (ID: 181)
add-features-to-set 181 --features 96 101 107

# Feature Set 158/560: vuhpsd_cuhslp_cfpsd_fs42 (ID: 182)
add-features-to-set 182 --features 96 101 108

# Feature Set 159/560: vuhpsd_cuhslp_cfslp_fs42 (ID: 183)
add-features-to-set 183 --features 96 101 109

# Feature Set 160/560: vuhpsd_cuhslp_cfsfm_fs42 (ID: 184)
add-features-to-set 184 --features 96 101 110

# Feature Set 161/560: vuhpsd_cuhsfm_vfsnr_fs42 (ID: 185)
add-features-to-set 185 --features 96 102 103

# Feature Set 162/560: vuhpsd_cuhsfm_vfpsd_fs42 (ID: 186)
add-features-to-set 186 --features 96 102 104

# Feature Set 163/560: vuhpsd_cuhsfm_vfslp_fs42 (ID: 187)
add-features-to-set 187 --features 96 102 105

# Feature Set 164/560: vuhpsd_cuhsfm_vfsfm_fs42 (ID: 188)
add-features-to-set 188 --features 96 102 106

# Feature Set 165/560: vuhpsd_cuhsfm_cfsnr_fs42 (ID: 189)
add-features-to-set 189 --features 96 102 107

# Feature Set 166/560: vuhpsd_cuhsfm_cfpsd_fs42 (ID: 190)
add-features-to-set 190 --features 96 102 108

# Feature Set 167/560: vuhpsd_cuhsfm_cfslp_fs42 (ID: 191)
add-features-to-set 191 --features 96 102 109

# Feature Set 168/560: vuhpsd_cuhsfm_cfsfm_fs42 (ID: 192)
add-features-to-set 192 --features 96 102 110

# Feature Set 169/560: vuhpsd_vfsnr_vfpsd_fs42 (ID: 193)
add-features-to-set 193 --features 96 103 104

# Feature Set 170/560: vuhpsd_vfsnr_vfslp_fs42 (ID: 194)
add-features-to-set 194 --features 96 103 105

# Feature Set 171/560: vuhpsd_vfsnr_vfsfm_fs42 (ID: 195)
add-features-to-set 195 --features 96 103 106

# Feature Set 172/560: vuhpsd_vfsnr_cfsnr_fs42 (ID: 196)
add-features-to-set 196 --features 96 103 107

# Feature Set 173/560: vuhpsd_vfsnr_cfpsd_fs42 (ID: 197)
add-features-to-set 197 --features 96 103 108

# Feature Set 174/560: vuhpsd_vfsnr_cfslp_fs42 (ID: 198)
add-features-to-set 198 --features 96 103 109

# Feature Set 175/560: vuhpsd_vfsnr_cfsfm_fs42 (ID: 199)
add-features-to-set 199 --features 96 103 110

# Feature Set 176/560: vuhpsd_vfpsd_vfslp_fs42 (ID: 200)
add-features-to-set 200 --features 96 104 105

# Feature Set 177/560: vuhpsd_vfpsd_vfsfm_fs42 (ID: 201)
add-features-to-set 201 --features 96 104 106

# Feature Set 178/560: vuhpsd_vfpsd_cfsnr_fs42 (ID: 202)
add-features-to-set 202 --features 96 104 107

# Feature Set 179/560: vuhpsd_vfpsd_cfpsd_fs42 (ID: 203)
add-features-to-set 203 --features 96 104 108

# Feature Set 180/560: vuhpsd_vfpsd_cfslp_fs42 (ID: 204)
add-features-to-set 204 --features 96 104 109

# Feature Set 181/560: vuhpsd_vfpsd_cfsfm_fs42 (ID: 205)
add-features-to-set 205 --features 96 104 110

# Feature Set 182/560: vuhpsd_vfslp_vfsfm_fs42 (ID: 206)
add-features-to-set 206 --features 96 105 106

# Feature Set 183/560: vuhpsd_vfslp_cfsnr_fs42 (ID: 207)
add-features-to-set 207 --features 96 105 107

# Feature Set 184/560: vuhpsd_vfslp_cfpsd_fs42 (ID: 208)
add-features-to-set 208 --features 96 105 108

# Feature Set 185/560: vuhpsd_vfslp_cfslp_fs42 (ID: 209)
add-features-to-set 209 --features 96 105 109

# Feature Set 186/560: vuhpsd_vfslp_cfsfm_fs42 (ID: 210)
add-features-to-set 210 --features 96 105 110

# Feature Set 187/560: vuhpsd_vfsfm_cfsnr_fs42 (ID: 211)
add-features-to-set 211 --features 96 106 107

# Feature Set 188/560: vuhpsd_vfsfm_cfpsd_fs42 (ID: 212)
add-features-to-set 212 --features 96 106 108

# Feature Set 189/560: vuhpsd_vfsfm_cfslp_fs42 (ID: 213)
add-features-to-set 213 --features 96 106 109

# Feature Set 190/560: vuhpsd_vfsfm_cfsfm_fs42 (ID: 214)
add-features-to-set 214 --features 96 106 110

# Feature Set 191/560: vuhpsd_cfsnr_cfpsd_fs42 (ID: 215)
add-features-to-set 215 --features 96 107 108

# Feature Set 192/560: vuhpsd_cfsnr_cfslp_fs42 (ID: 216)
add-features-to-set 216 --features 96 107 109

# Feature Set 193/560: vuhpsd_cfsnr_cfsfm_fs42 (ID: 217)
add-features-to-set 217 --features 96 107 110

# Feature Set 194/560: vuhpsd_cfpsd_cfslp_fs42 (ID: 218)
add-features-to-set 218 --features 96 108 109

# Feature Set 195/560: vuhpsd_cfpsd_cfsfm_fs42 (ID: 219)
add-features-to-set 219 --features 96 108 110

# Feature Set 196/560: vuhpsd_cfslp_cfsfm_fs42 (ID: 220)
add-features-to-set 220 --features 96 109 110

# Feature Set 197/560: vuhslp_vuhsfm_cuhsnr_fs42 (ID: 221)
add-features-to-set 221 --features 97 98 99

# Feature Set 198/560: vuhslp_vuhsfm_cuhpsd_fs42 (ID: 222)
add-features-to-set 222 --features 97 98 100

# Feature Set 199/560: vuhslp_vuhsfm_cuhslp_fs42 (ID: 223)
add-features-to-set 223 --features 97 98 101

# Feature Set 200/560: vuhslp_vuhsfm_cuhsfm_fs42 (ID: 224)
add-features-to-set 224 --features 97 98 102

# Progress: 200/560 feature sets fixed (35%)

# Feature Set 201/560: vuhslp_vuhsfm_vfsnr_fs42 (ID: 225)
add-features-to-set 225 --features 97 98 103

# Feature Set 202/560: vuhslp_vuhsfm_vfpsd_fs42 (ID: 226)
add-features-to-set 226 --features 97 98 104

# Feature Set 203/560: vuhslp_vuhsfm_vfslp_fs42 (ID: 227)
add-features-to-set 227 --features 97 98 105

# Feature Set 204/560: vuhslp_vuhsfm_vfsfm_fs42 (ID: 228)
add-features-to-set 228 --features 97 98 106

# Feature Set 205/560: vuhslp_vuhsfm_cfsnr_fs42 (ID: 229)
add-features-to-set 229 --features 97 98 107

# Feature Set 206/560: vuhslp_vuhsfm_cfpsd_fs42 (ID: 230)
add-features-to-set 230 --features 97 98 108

# Feature Set 207/560: vuhslp_vuhsfm_cfslp_fs42 (ID: 231)
add-features-to-set 231 --features 97 98 109

# Feature Set 208/560: vuhslp_vuhsfm_cfsfm_fs42 (ID: 232)
add-features-to-set 232 --features 97 98 110

# Feature Set 209/560: vuhslp_cuhsnr_cuhpsd_fs42 (ID: 233)
add-features-to-set 233 --features 97 99 100

# Feature Set 210/560: vuhslp_cuhsnr_cuhslp_fs42 (ID: 234)
add-features-to-set 234 --features 97 99 101

# Feature Set 211/560: vuhslp_cuhsnr_cuhsfm_fs42 (ID: 235)
add-features-to-set 235 --features 97 99 102

# Feature Set 212/560: vuhslp_cuhsnr_vfsnr_fs42 (ID: 236)
add-features-to-set 236 --features 97 99 103

# Feature Set 213/560: vuhslp_cuhsnr_vfpsd_fs42 (ID: 237)
add-features-to-set 237 --features 97 99 104

# Feature Set 214/560: vuhslp_cuhsnr_vfslp_fs42 (ID: 238)
add-features-to-set 238 --features 97 99 105

# Feature Set 215/560: vuhslp_cuhsnr_vfsfm_fs42 (ID: 239)
add-features-to-set 239 --features 97 99 106

# Feature Set 216/560: vuhslp_cuhsnr_cfsnr_fs42 (ID: 240)
add-features-to-set 240 --features 97 99 107

# Feature Set 217/560: vuhslp_cuhsnr_cfpsd_fs42 (ID: 241)
add-features-to-set 241 --features 97 99 108

# Feature Set 218/560: vuhslp_cuhsnr_cfslp_fs42 (ID: 242)
add-features-to-set 242 --features 97 99 109

# Feature Set 219/560: vuhslp_cuhsnr_cfsfm_fs42 (ID: 243)
add-features-to-set 243 --features 97 99 110

# Feature Set 220/560: vuhslp_cuhpsd_cuhslp_fs42 (ID: 244)
add-features-to-set 244 --features 97 100 101

# Feature Set 221/560: vuhslp_cuhpsd_cuhsfm_fs42 (ID: 245)
add-features-to-set 245 --features 97 100 102

# Feature Set 222/560: vuhslp_cuhpsd_vfsnr_fs42 (ID: 246)
add-features-to-set 246 --features 97 100 103

# Feature Set 223/560: vuhslp_cuhpsd_vfpsd_fs42 (ID: 247)
add-features-to-set 247 --features 97 100 104

# Feature Set 224/560: vuhslp_cuhpsd_vfslp_fs42 (ID: 248)
add-features-to-set 248 --features 97 100 105

# Feature Set 225/560: vuhslp_cuhpsd_vfsfm_fs42 (ID: 249)
add-features-to-set 249 --features 97 100 106

# Feature Set 226/560: vuhslp_cuhpsd_cfsnr_fs42 (ID: 250)
add-features-to-set 250 --features 97 100 107

# Feature Set 227/560: vuhslp_cuhpsd_cfpsd_fs42 (ID: 251)
add-features-to-set 251 --features 97 100 108

# Feature Set 228/560: vuhslp_cuhpsd_cfslp_fs42 (ID: 252)
add-features-to-set 252 --features 97 100 109

# Feature Set 229/560: vuhslp_cuhpsd_cfsfm_fs42 (ID: 253)
add-features-to-set 253 --features 97 100 110

# Feature Set 230/560: vuhslp_cuhslp_cuhsfm_fs42 (ID: 254)
add-features-to-set 254 --features 97 101 102

# Feature Set 231/560: vuhslp_cuhslp_vfsnr_fs42 (ID: 255)
add-features-to-set 255 --features 97 101 103

# Feature Set 232/560: vuhslp_cuhslp_vfpsd_fs42 (ID: 256)
add-features-to-set 256 --features 97 101 104

# Feature Set 233/560: vuhslp_cuhslp_vfslp_fs42 (ID: 257)
add-features-to-set 257 --features 97 101 105

# Feature Set 234/560: vuhslp_cuhslp_vfsfm_fs42 (ID: 258)
add-features-to-set 258 --features 97 101 106

# Feature Set 235/560: vuhslp_cuhslp_cfsnr_fs42 (ID: 259)
add-features-to-set 259 --features 97 101 107

# Feature Set 236/560: vuhslp_cuhslp_cfpsd_fs42 (ID: 260)
add-features-to-set 260 --features 97 101 108

# Feature Set 237/560: vuhslp_cuhslp_cfslp_fs42 (ID: 261)
add-features-to-set 261 --features 97 101 109

# Feature Set 238/560: vuhslp_cuhslp_cfsfm_fs42 (ID: 262)
add-features-to-set 262 --features 97 101 110

# Feature Set 239/560: vuhslp_cuhsfm_vfsnr_fs42 (ID: 263)
add-features-to-set 263 --features 97 102 103

# Feature Set 240/560: vuhslp_cuhsfm_vfpsd_fs42 (ID: 264)
add-features-to-set 264 --features 97 102 104

# Feature Set 241/560: vuhslp_cuhsfm_vfslp_fs42 (ID: 265)
add-features-to-set 265 --features 97 102 105

# Feature Set 242/560: vuhslp_cuhsfm_vfsfm_fs42 (ID: 266)
add-features-to-set 266 --features 97 102 106

# Feature Set 243/560: vuhslp_cuhsfm_cfsnr_fs42 (ID: 267)
add-features-to-set 267 --features 97 102 107

# Feature Set 244/560: vuhslp_cuhsfm_cfpsd_fs42 (ID: 268)
add-features-to-set 268 --features 97 102 108

# Feature Set 245/560: vuhslp_cuhsfm_cfslp_fs42 (ID: 269)
add-features-to-set 269 --features 97 102 109

# Feature Set 246/560: vuhslp_cuhsfm_cfsfm_fs42 (ID: 270)
add-features-to-set 270 --features 97 102 110

# Feature Set 247/560: vuhslp_vfsnr_vfpsd_fs42 (ID: 271)
add-features-to-set 271 --features 97 103 104

# Feature Set 248/560: vuhslp_vfsnr_vfslp_fs42 (ID: 272)
add-features-to-set 272 --features 97 103 105

# Feature Set 249/560: vuhslp_vfsnr_vfsfm_fs42 (ID: 273)
add-features-to-set 273 --features 97 103 106

# Feature Set 250/560: vuhslp_vfsnr_cfsnr_fs42 (ID: 274)
add-features-to-set 274 --features 97 103 107

# Progress: 250/560 feature sets fixed (44%)

# Feature Set 251/560: vuhslp_vfsnr_cfpsd_fs42 (ID: 275)
add-features-to-set 275 --features 97 103 108

# Feature Set 252/560: vuhslp_vfsnr_cfslp_fs42 (ID: 276)
add-features-to-set 276 --features 97 103 109

# Feature Set 253/560: vuhslp_vfsnr_cfsfm_fs42 (ID: 277)
add-features-to-set 277 --features 97 103 110

# Feature Set 254/560: vuhslp_vfpsd_vfslp_fs42 (ID: 278)
add-features-to-set 278 --features 97 104 105

# Feature Set 255/560: vuhslp_vfpsd_vfsfm_fs42 (ID: 279)
add-features-to-set 279 --features 97 104 106

# Feature Set 256/560: vuhslp_vfpsd_cfsnr_fs42 (ID: 280)
add-features-to-set 280 --features 97 104 107

# Feature Set 257/560: vuhslp_vfpsd_cfpsd_fs42 (ID: 281)
add-features-to-set 281 --features 97 104 108

# Feature Set 258/560: vuhslp_vfpsd_cfslp_fs42 (ID: 282)
add-features-to-set 282 --features 97 104 109

# Feature Set 259/560: vuhslp_vfpsd_cfsfm_fs42 (ID: 283)
add-features-to-set 283 --features 97 104 110

# Feature Set 260/560: vuhslp_vfslp_vfsfm_fs42 (ID: 284)
add-features-to-set 284 --features 97 105 106

# Feature Set 261/560: vuhslp_vfslp_cfsnr_fs42 (ID: 285)
add-features-to-set 285 --features 97 105 107

# Feature Set 262/560: vuhslp_vfslp_cfpsd_fs42 (ID: 286)
add-features-to-set 286 --features 97 105 108

# Feature Set 263/560: vuhslp_vfslp_cfslp_fs42 (ID: 287)
add-features-to-set 287 --features 97 105 109

# Feature Set 264/560: vuhslp_vfslp_cfsfm_fs42 (ID: 288)
add-features-to-set 288 --features 97 105 110

# Feature Set 265/560: vuhslp_vfsfm_cfsnr_fs42 (ID: 289)
add-features-to-set 289 --features 97 106 107

# Feature Set 266/560: vuhslp_vfsfm_cfpsd_fs42 (ID: 290)
add-features-to-set 290 --features 97 106 108

# Feature Set 267/560: vuhslp_vfsfm_cfslp_fs42 (ID: 291)
add-features-to-set 291 --features 97 106 109

# Feature Set 268/560: vuhslp_vfsfm_cfsfm_fs42 (ID: 292)
add-features-to-set 292 --features 97 106 110

# Feature Set 269/560: vuhslp_cfsnr_cfpsd_fs42 (ID: 293)
add-features-to-set 293 --features 97 107 108

# Feature Set 270/560: vuhslp_cfsnr_cfslp_fs42 (ID: 294)
add-features-to-set 294 --features 97 107 109

# Feature Set 271/560: vuhslp_cfsnr_cfsfm_fs42 (ID: 295)
add-features-to-set 295 --features 97 107 110

# Feature Set 272/560: vuhslp_cfpsd_cfslp_fs42 (ID: 296)
add-features-to-set 296 --features 97 108 109

# Feature Set 273/560: vuhslp_cfpsd_cfsfm_fs42 (ID: 297)
add-features-to-set 297 --features 97 108 110

# Feature Set 274/560: vuhslp_cfslp_cfsfm_fs42 (ID: 298)
add-features-to-set 298 --features 97 109 110

# Feature Set 275/560: vuhsfm_cuhsnr_cuhpsd_fs42 (ID: 299)
add-features-to-set 299 --features 98 99 100

# Feature Set 276/560: vuhsfm_cuhsnr_cuhslp_fs42 (ID: 300)
add-features-to-set 300 --features 98 99 101

# Feature Set 277/560: vuhsfm_cuhsnr_cuhsfm_fs42 (ID: 301)
add-features-to-set 301 --features 98 99 102

# Feature Set 278/560: vuhsfm_cuhsnr_vfsnr_fs42 (ID: 302)
add-features-to-set 302 --features 98 99 103

# Feature Set 279/560: vuhsfm_cuhsnr_vfpsd_fs42 (ID: 303)
add-features-to-set 303 --features 98 99 104

# Feature Set 280/560: vuhsfm_cuhsnr_vfslp_fs42 (ID: 304)
add-features-to-set 304 --features 98 99 105

# Feature Set 281/560: vuhsfm_cuhsnr_vfsfm_fs42 (ID: 305)
add-features-to-set 305 --features 98 99 106

# Feature Set 282/560: vuhsfm_cuhsnr_cfsnr_fs42 (ID: 306)
add-features-to-set 306 --features 98 99 107

# Feature Set 283/560: vuhsfm_cuhsnr_cfpsd_fs42 (ID: 307)
add-features-to-set 307 --features 98 99 108

# Feature Set 284/560: vuhsfm_cuhsnr_cfslp_fs42 (ID: 308)
add-features-to-set 308 --features 98 99 109

# Feature Set 285/560: vuhsfm_cuhsnr_cfsfm_fs42 (ID: 309)
add-features-to-set 309 --features 98 99 110

# Feature Set 286/560: vuhsfm_cuhpsd_cuhslp_fs42 (ID: 310)
add-features-to-set 310 --features 98 100 101

# Feature Set 287/560: vuhsfm_cuhpsd_cuhsfm_fs42 (ID: 311)
add-features-to-set 311 --features 98 100 102

# Feature Set 288/560: vuhsfm_cuhpsd_vfsnr_fs42 (ID: 312)
add-features-to-set 312 --features 98 100 103

# Feature Set 289/560: vuhsfm_cuhpsd_vfpsd_fs42 (ID: 313)
add-features-to-set 313 --features 98 100 104

# Feature Set 290/560: vuhsfm_cuhpsd_vfslp_fs42 (ID: 314)
add-features-to-set 314 --features 98 100 105

# Feature Set 291/560: vuhsfm_cuhpsd_vfsfm_fs42 (ID: 315)
add-features-to-set 315 --features 98 100 106

# Feature Set 292/560: vuhsfm_cuhpsd_cfsnr_fs42 (ID: 316)
add-features-to-set 316 --features 98 100 107

# Feature Set 293/560: vuhsfm_cuhpsd_cfpsd_fs42 (ID: 317)
add-features-to-set 317 --features 98 100 108

# Feature Set 294/560: vuhsfm_cuhpsd_cfslp_fs42 (ID: 318)
add-features-to-set 318 --features 98 100 109

# Feature Set 295/560: vuhsfm_cuhpsd_cfsfm_fs42 (ID: 319)
add-features-to-set 319 --features 98 100 110

# Feature Set 296/560: vuhsfm_cuhslp_cuhsfm_fs42 (ID: 320)
add-features-to-set 320 --features 98 101 102

# Feature Set 297/560: vuhsfm_cuhslp_vfsnr_fs42 (ID: 321)
add-features-to-set 321 --features 98 101 103

# Feature Set 298/560: vuhsfm_cuhslp_vfpsd_fs42 (ID: 322)
add-features-to-set 322 --features 98 101 104

# Feature Set 299/560: vuhsfm_cuhslp_vfslp_fs42 (ID: 323)
add-features-to-set 323 --features 98 101 105

# Feature Set 300/560: vuhsfm_cuhslp_vfsfm_fs42 (ID: 324)
add-features-to-set 324 --features 98 101 106

# Progress: 300/560 feature sets fixed (53%)

# Feature Set 301/560: vuhsfm_cuhslp_cfsnr_fs42 (ID: 325)
add-features-to-set 325 --features 98 101 107

# Feature Set 302/560: vuhsfm_cuhslp_cfpsd_fs42 (ID: 326)
add-features-to-set 326 --features 98 101 108

# Feature Set 303/560: vuhsfm_cuhslp_cfslp_fs42 (ID: 327)
add-features-to-set 327 --features 98 101 109

# Feature Set 304/560: vuhsfm_cuhslp_cfsfm_fs42 (ID: 328)
add-features-to-set 328 --features 98 101 110

# Feature Set 305/560: vuhsfm_cuhsfm_vfsnr_fs42 (ID: 329)
add-features-to-set 329 --features 98 102 103

# Feature Set 306/560: vuhsfm_cuhsfm_vfpsd_fs42 (ID: 330)
add-features-to-set 330 --features 98 102 104

# Feature Set 307/560: vuhsfm_cuhsfm_vfslp_fs42 (ID: 331)
add-features-to-set 331 --features 98 102 105

# Feature Set 308/560: vuhsfm_cuhsfm_vfsfm_fs42 (ID: 332)
add-features-to-set 332 --features 98 102 106

# Feature Set 309/560: vuhsfm_cuhsfm_cfsnr_fs42 (ID: 333)
add-features-to-set 333 --features 98 102 107

# Feature Set 310/560: vuhsfm_cuhsfm_cfpsd_fs42 (ID: 334)
add-features-to-set 334 --features 98 102 108

# Feature Set 311/560: vuhsfm_cuhsfm_cfslp_fs42 (ID: 335)
add-features-to-set 335 --features 98 102 109

# Feature Set 312/560: vuhsfm_cuhsfm_cfsfm_fs42 (ID: 336)
add-features-to-set 336 --features 98 102 110

# Feature Set 313/560: vuhsfm_vfsnr_vfpsd_fs42 (ID: 337)
add-features-to-set 337 --features 98 103 104

# Feature Set 314/560: vuhsfm_vfsnr_vfslp_fs42 (ID: 338)
add-features-to-set 338 --features 98 103 105

# Feature Set 315/560: vuhsfm_vfsnr_vfsfm_fs42 (ID: 339)
add-features-to-set 339 --features 98 103 106

# Feature Set 316/560: vuhsfm_vfsnr_cfsnr_fs42 (ID: 340)
add-features-to-set 340 --features 98 103 107

# Feature Set 317/560: vuhsfm_vfsnr_cfpsd_fs42 (ID: 341)
add-features-to-set 341 --features 98 103 108

# Feature Set 318/560: vuhsfm_vfsnr_cfslp_fs42 (ID: 342)
add-features-to-set 342 --features 98 103 109

# Feature Set 319/560: vuhsfm_vfsnr_cfsfm_fs42 (ID: 343)
add-features-to-set 343 --features 98 103 110

# Feature Set 320/560: vuhsfm_vfpsd_vfslp_fs42 (ID: 344)
add-features-to-set 344 --features 98 104 105

# Feature Set 321/560: vuhsfm_vfpsd_vfsfm_fs42 (ID: 345)
add-features-to-set 345 --features 98 104 106

# Feature Set 322/560: vuhsfm_vfpsd_cfsnr_fs42 (ID: 346)
add-features-to-set 346 --features 98 104 107

# Feature Set 323/560: vuhsfm_vfpsd_cfpsd_fs42 (ID: 347)
add-features-to-set 347 --features 98 104 108

# Feature Set 324/560: vuhsfm_vfpsd_cfslp_fs42 (ID: 348)
add-features-to-set 348 --features 98 104 109

# Feature Set 325/560: vuhsfm_vfpsd_cfsfm_fs42 (ID: 349)
add-features-to-set 349 --features 98 104 110

# Feature Set 326/560: vuhsfm_vfslp_vfsfm_fs42 (ID: 350)
add-features-to-set 350 --features 98 105 106

# Feature Set 327/560: vuhsfm_vfslp_cfsnr_fs42 (ID: 351)
add-features-to-set 351 --features 98 105 107

# Feature Set 328/560: vuhsfm_vfslp_cfpsd_fs42 (ID: 352)
add-features-to-set 352 --features 98 105 108

# Feature Set 329/560: vuhsfm_vfslp_cfslp_fs42 (ID: 353)
add-features-to-set 353 --features 98 105 109

# Feature Set 330/560: vuhsfm_vfslp_cfsfm_fs42 (ID: 354)
add-features-to-set 354 --features 98 105 110

# Feature Set 331/560: vuhsfm_vfsfm_cfsnr_fs42 (ID: 355)
add-features-to-set 355 --features 98 106 107

# Feature Set 332/560: vuhsfm_vfsfm_cfpsd_fs42 (ID: 356)
add-features-to-set 356 --features 98 106 108

# Feature Set 333/560: vuhsfm_vfsfm_cfslp_fs42 (ID: 357)
add-features-to-set 357 --features 98 106 109

# Feature Set 334/560: vuhsfm_vfsfm_cfsfm_fs42 (ID: 358)
add-features-to-set 358 --features 98 106 110

# Feature Set 335/560: vuhsfm_cfsnr_cfpsd_fs42 (ID: 359)
add-features-to-set 359 --features 98 107 108

# Feature Set 336/560: vuhsfm_cfsnr_cfslp_fs42 (ID: 360)
add-features-to-set 360 --features 98 107 109

# Feature Set 337/560: vuhsfm_cfsnr_cfsfm_fs42 (ID: 361)
add-features-to-set 361 --features 98 107 110

# Feature Set 338/560: vuhsfm_cfpsd_cfslp_fs42 (ID: 362)
add-features-to-set 362 --features 98 108 109

# Feature Set 339/560: vuhsfm_cfpsd_cfsfm_fs42 (ID: 363)
add-features-to-set 363 --features 98 108 110

# Feature Set 340/560: vuhsfm_cfslp_cfsfm_fs42 (ID: 364)
add-features-to-set 364 --features 98 109 110

# Feature Set 341/560: cuhsnr_cuhpsd_cuhslp_fs42 (ID: 365)
add-features-to-set 365 --features 99 100 101

# Feature Set 342/560: cuhsnr_cuhpsd_cuhsfm_fs42 (ID: 366)
add-features-to-set 366 --features 99 100 102

# Feature Set 343/560: cuhsnr_cuhpsd_vfsnr_fs42 (ID: 367)
add-features-to-set 367 --features 99 100 103

# Feature Set 344/560: cuhsnr_cuhpsd_vfpsd_fs42 (ID: 368)
add-features-to-set 368 --features 99 100 104

# Feature Set 345/560: cuhsnr_cuhpsd_vfslp_fs42 (ID: 369)
add-features-to-set 369 --features 99 100 105

# Feature Set 346/560: cuhsnr_cuhpsd_vfsfm_fs42 (ID: 370)
add-features-to-set 370 --features 99 100 106

# Feature Set 347/560: cuhsnr_cuhpsd_cfsnr_fs42 (ID: 371)
add-features-to-set 371 --features 99 100 107

# Feature Set 348/560: cuhsnr_cuhpsd_cfpsd_fs42 (ID: 372)
add-features-to-set 372 --features 99 100 108

# Feature Set 349/560: cuhsnr_cuhpsd_cfslp_fs42 (ID: 373)
add-features-to-set 373 --features 99 100 109

# Feature Set 350/560: cuhsnr_cuhpsd_cfsfm_fs42 (ID: 374)
add-features-to-set 374 --features 99 100 110

# Progress: 350/560 feature sets fixed (62%)

# Feature Set 351/560: cuhsnr_cuhslp_cuhsfm_fs42 (ID: 375)
add-features-to-set 375 --features 99 101 102

# Feature Set 352/560: cuhsnr_cuhslp_vfsnr_fs42 (ID: 376)
add-features-to-set 376 --features 99 101 103

# Feature Set 353/560: cuhsnr_cuhslp_vfpsd_fs42 (ID: 377)
add-features-to-set 377 --features 99 101 104

# Feature Set 354/560: cuhsnr_cuhslp_vfslp_fs42 (ID: 378)
add-features-to-set 378 --features 99 101 105

# Feature Set 355/560: cuhsnr_cuhslp_vfsfm_fs42 (ID: 379)
add-features-to-set 379 --features 99 101 106

# Feature Set 356/560: cuhsnr_cuhslp_cfsnr_fs42 (ID: 380)
add-features-to-set 380 --features 99 101 107

# Feature Set 357/560: cuhsnr_cuhslp_cfpsd_fs42 (ID: 381)
add-features-to-set 381 --features 99 101 108

# Feature Set 358/560: cuhsnr_cuhslp_cfslp_fs42 (ID: 382)
add-features-to-set 382 --features 99 101 109

# Feature Set 359/560: cuhsnr_cuhslp_cfsfm_fs42 (ID: 383)
add-features-to-set 383 --features 99 101 110

# Feature Set 360/560: cuhsnr_cuhsfm_vfsnr_fs42 (ID: 384)
add-features-to-set 384 --features 99 102 103

# Feature Set 361/560: cuhsnr_cuhsfm_vfpsd_fs42 (ID: 385)
add-features-to-set 385 --features 99 102 104

# Feature Set 362/560: cuhsnr_cuhsfm_vfslp_fs42 (ID: 386)
add-features-to-set 386 --features 99 102 105

# Feature Set 363/560: cuhsnr_cuhsfm_vfsfm_fs42 (ID: 387)
add-features-to-set 387 --features 99 102 106

# Feature Set 364/560: cuhsnr_cuhsfm_cfsnr_fs42 (ID: 388)
add-features-to-set 388 --features 99 102 107

# Feature Set 365/560: cuhsnr_cuhsfm_cfpsd_fs42 (ID: 389)
add-features-to-set 389 --features 99 102 108

# Feature Set 366/560: cuhsnr_cuhsfm_cfslp_fs42 (ID: 390)
add-features-to-set 390 --features 99 102 109

# Feature Set 367/560: cuhsnr_cuhsfm_cfsfm_fs42 (ID: 391)
add-features-to-set 391 --features 99 102 110

# Feature Set 368/560: cuhsnr_vfsnr_vfpsd_fs42 (ID: 392)
add-features-to-set 392 --features 99 103 104

# Feature Set 369/560: cuhsnr_vfsnr_vfslp_fs42 (ID: 393)
add-features-to-set 393 --features 99 103 105

# Feature Set 370/560: cuhsnr_vfsnr_vfsfm_fs42 (ID: 394)
add-features-to-set 394 --features 99 103 106

# Feature Set 371/560: cuhsnr_vfsnr_cfsnr_fs42 (ID: 395)
add-features-to-set 395 --features 99 103 107

# Feature Set 372/560: cuhsnr_vfsnr_cfpsd_fs42 (ID: 396)
add-features-to-set 396 --features 99 103 108

# Feature Set 373/560: cuhsnr_vfsnr_cfslp_fs42 (ID: 397)
add-features-to-set 397 --features 99 103 109

# Feature Set 374/560: cuhsnr_vfsnr_cfsfm_fs42 (ID: 398)
add-features-to-set 398 --features 99 103 110

# Feature Set 375/560: cuhsnr_vfpsd_vfslp_fs42 (ID: 399)
add-features-to-set 399 --features 99 104 105

# Feature Set 376/560: cuhsnr_vfpsd_vfsfm_fs42 (ID: 400)
add-features-to-set 400 --features 99 104 106

# Feature Set 377/560: cuhsnr_vfpsd_cfsnr_fs42 (ID: 401)
add-features-to-set 401 --features 99 104 107

# Feature Set 378/560: cuhsnr_vfpsd_cfpsd_fs42 (ID: 402)
add-features-to-set 402 --features 99 104 108

# Feature Set 379/560: cuhsnr_vfpsd_cfslp_fs42 (ID: 403)
add-features-to-set 403 --features 99 104 109

# Feature Set 380/560: cuhsnr_vfpsd_cfsfm_fs42 (ID: 404)
add-features-to-set 404 --features 99 104 110

# Feature Set 381/560: cuhsnr_vfslp_vfsfm_fs42 (ID: 405)
add-features-to-set 405 --features 99 105 106

# Feature Set 382/560: cuhsnr_vfslp_cfsnr_fs42 (ID: 406)
add-features-to-set 406 --features 99 105 107

# Feature Set 383/560: cuhsnr_vfslp_cfpsd_fs42 (ID: 407)
add-features-to-set 407 --features 99 105 108

# Feature Set 384/560: cuhsnr_vfslp_cfslp_fs42 (ID: 408)
add-features-to-set 408 --features 99 105 109

# Feature Set 385/560: cuhsnr_vfslp_cfsfm_fs42 (ID: 409)
add-features-to-set 409 --features 99 105 110

# Feature Set 386/560: cuhsnr_vfsfm_cfsnr_fs42 (ID: 410)
add-features-to-set 410 --features 99 106 107

# Feature Set 387/560: cuhsnr_vfsfm_cfpsd_fs42 (ID: 411)
add-features-to-set 411 --features 99 106 108

# Feature Set 388/560: cuhsnr_vfsfm_cfslp_fs42 (ID: 412)
add-features-to-set 412 --features 99 106 109

# Feature Set 389/560: cuhsnr_vfsfm_cfsfm_fs42 (ID: 413)
add-features-to-set 413 --features 99 106 110

# Feature Set 390/560: cuhsnr_cfsnr_cfpsd_fs42 (ID: 414)
add-features-to-set 414 --features 99 107 108

# Feature Set 391/560: cuhsnr_cfsnr_cfslp_fs42 (ID: 415)
add-features-to-set 415 --features 99 107 109

# Feature Set 392/560: cuhsnr_cfsnr_cfsfm_fs42 (ID: 416)
add-features-to-set 416 --features 99 107 110

# Feature Set 393/560: cuhsnr_cfpsd_cfslp_fs42 (ID: 417)
add-features-to-set 417 --features 99 108 109

# Feature Set 394/560: cuhsnr_cfpsd_cfsfm_fs42 (ID: 418)
add-features-to-set 418 --features 99 108 110

# Feature Set 395/560: cuhsnr_cfslp_cfsfm_fs42 (ID: 419)
add-features-to-set 419 --features 99 109 110

# Feature Set 396/560: cuhpsd_cuhslp_cuhsfm_fs42 (ID: 420)
add-features-to-set 420 --features 100 101 102

# Feature Set 397/560: cuhpsd_cuhslp_vfsnr_fs42 (ID: 421)
add-features-to-set 421 --features 100 101 103

# Feature Set 398/560: cuhpsd_cuhslp_vfpsd_fs42 (ID: 422)
add-features-to-set 422 --features 100 101 104

# Feature Set 399/560: cuhpsd_cuhslp_vfslp_fs42 (ID: 423)
add-features-to-set 423 --features 100 101 105

# Feature Set 400/560: cuhpsd_cuhslp_vfsfm_fs42 (ID: 424)
add-features-to-set 424 --features 100 101 106

# Progress: 400/560 feature sets fixed (71%)

# Feature Set 401/560: cuhpsd_cuhslp_cfsnr_fs42 (ID: 425)
add-features-to-set 425 --features 100 101 107

# Feature Set 402/560: cuhpsd_cuhslp_cfpsd_fs42 (ID: 426)
add-features-to-set 426 --features 100 101 108

# Feature Set 403/560: cuhpsd_cuhslp_cfslp_fs42 (ID: 427)
add-features-to-set 427 --features 100 101 109

# Feature Set 404/560: cuhpsd_cuhslp_cfsfm_fs42 (ID: 428)
add-features-to-set 428 --features 100 101 110

# Feature Set 405/560: cuhpsd_cuhsfm_vfsnr_fs42 (ID: 429)
add-features-to-set 429 --features 100 102 103

# Feature Set 406/560: cuhpsd_cuhsfm_vfpsd_fs42 (ID: 430)
add-features-to-set 430 --features 100 102 104

# Feature Set 407/560: cuhpsd_cuhsfm_vfslp_fs42 (ID: 431)
add-features-to-set 431 --features 100 102 105

# Feature Set 408/560: cuhpsd_cuhsfm_vfsfm_fs42 (ID: 432)
add-features-to-set 432 --features 100 102 106

# Feature Set 409/560: cuhpsd_cuhsfm_cfsnr_fs42 (ID: 433)
add-features-to-set 433 --features 100 102 107

# Feature Set 410/560: cuhpsd_cuhsfm_cfpsd_fs42 (ID: 434)
add-features-to-set 434 --features 100 102 108

# Feature Set 411/560: cuhpsd_cuhsfm_cfslp_fs42 (ID: 435)
add-features-to-set 435 --features 100 102 109

# Feature Set 412/560: cuhpsd_cuhsfm_cfsfm_fs42 (ID: 436)
add-features-to-set 436 --features 100 102 110

# Feature Set 413/560: cuhpsd_vfsnr_vfpsd_fs42 (ID: 437)
add-features-to-set 437 --features 100 103 104

# Feature Set 414/560: cuhpsd_vfsnr_vfslp_fs42 (ID: 438)
add-features-to-set 438 --features 100 103 105

# Feature Set 415/560: cuhpsd_vfsnr_vfsfm_fs42 (ID: 439)
add-features-to-set 439 --features 100 103 106

# Feature Set 416/560: cuhpsd_vfsnr_cfsnr_fs42 (ID: 440)
add-features-to-set 440 --features 100 103 107

# Feature Set 417/560: cuhpsd_vfsnr_cfpsd_fs42 (ID: 441)
add-features-to-set 441 --features 100 103 108

# Feature Set 418/560: cuhpsd_vfsnr_cfslp_fs42 (ID: 442)
add-features-to-set 442 --features 100 103 109

# Feature Set 419/560: cuhpsd_vfsnr_cfsfm_fs42 (ID: 443)
add-features-to-set 443 --features 100 103 110

# Feature Set 420/560: cuhpsd_vfpsd_vfslp_fs42 (ID: 444)
add-features-to-set 444 --features 100 104 105

# Feature Set 421/560: cuhpsd_vfpsd_vfsfm_fs42 (ID: 445)
add-features-to-set 445 --features 100 104 106

# Feature Set 422/560: cuhpsd_vfpsd_cfsnr_fs42 (ID: 446)
add-features-to-set 446 --features 100 104 107

# Feature Set 423/560: cuhpsd_vfpsd_cfpsd_fs42 (ID: 447)
add-features-to-set 447 --features 100 104 108

# Feature Set 424/560: cuhpsd_vfpsd_cfslp_fs42 (ID: 448)
add-features-to-set 448 --features 100 104 109

# Feature Set 425/560: cuhpsd_vfpsd_cfsfm_fs42 (ID: 449)
add-features-to-set 449 --features 100 104 110

# Feature Set 426/560: cuhpsd_vfslp_vfsfm_fs42 (ID: 450)
add-features-to-set 450 --features 100 105 106

# Feature Set 427/560: cuhpsd_vfslp_cfsnr_fs42 (ID: 451)
add-features-to-set 451 --features 100 105 107

# Feature Set 428/560: cuhpsd_vfslp_cfpsd_fs42 (ID: 452)
add-features-to-set 452 --features 100 105 108

# Feature Set 429/560: cuhpsd_vfslp_cfslp_fs42 (ID: 453)
add-features-to-set 453 --features 100 105 109

# Feature Set 430/560: cuhpsd_vfslp_cfsfm_fs42 (ID: 454)
add-features-to-set 454 --features 100 105 110

# Feature Set 431/560: cuhpsd_vfsfm_cfsnr_fs42 (ID: 455)
add-features-to-set 455 --features 100 106 107

# Feature Set 432/560: cuhpsd_vfsfm_cfpsd_fs42 (ID: 456)
add-features-to-set 456 --features 100 106 108

# Feature Set 433/560: cuhpsd_vfsfm_cfslp_fs42 (ID: 457)
add-features-to-set 457 --features 100 106 109

# Feature Set 434/560: cuhpsd_vfsfm_cfsfm_fs42 (ID: 458)
add-features-to-set 458 --features 100 106 110

# Feature Set 435/560: cuhpsd_cfsnr_cfpsd_fs42 (ID: 459)
add-features-to-set 459 --features 100 107 108

# Feature Set 436/560: cuhpsd_cfsnr_cfslp_fs42 (ID: 460)
add-features-to-set 460 --features 100 107 109

# Feature Set 437/560: cuhpsd_cfsnr_cfsfm_fs42 (ID: 461)
add-features-to-set 461 --features 100 107 110

# Feature Set 438/560: cuhpsd_cfpsd_cfslp_fs42 (ID: 462)
add-features-to-set 462 --features 100 108 109

# Feature Set 439/560: cuhpsd_cfpsd_cfsfm_fs42 (ID: 463)
add-features-to-set 463 --features 100 108 110

# Feature Set 440/560: cuhpsd_cfslp_cfsfm_fs42 (ID: 464)
add-features-to-set 464 --features 100 109 110

# Feature Set 441/560: cuhslp_cuhsfm_vfsnr_fs42 (ID: 465)
add-features-to-set 465 --features 101 102 103

# Feature Set 442/560: cuhslp_cuhsfm_vfpsd_fs42 (ID: 466)
add-features-to-set 466 --features 101 102 104

# Feature Set 443/560: cuhslp_cuhsfm_vfslp_fs42 (ID: 467)
add-features-to-set 467 --features 101 102 105

# Feature Set 444/560: cuhslp_cuhsfm_vfsfm_fs42 (ID: 468)
add-features-to-set 468 --features 101 102 106

# Feature Set 445/560: cuhslp_cuhsfm_cfsnr_fs42 (ID: 469)
add-features-to-set 469 --features 101 102 107

# Feature Set 446/560: cuhslp_cuhsfm_cfpsd_fs42 (ID: 470)
add-features-to-set 470 --features 101 102 108

# Feature Set 447/560: cuhslp_cuhsfm_cfslp_fs42 (ID: 471)
add-features-to-set 471 --features 101 102 109

# Feature Set 448/560: cuhslp_cuhsfm_cfsfm_fs42 (ID: 472)
add-features-to-set 472 --features 101 102 110

# Feature Set 449/560: cuhslp_vfsnr_vfpsd_fs42 (ID: 473)
add-features-to-set 473 --features 101 103 104

# Feature Set 450/560: cuhslp_vfsnr_vfslp_fs42 (ID: 474)
add-features-to-set 474 --features 101 103 105

# Progress: 450/560 feature sets fixed (80%)

# Feature Set 451/560: cuhslp_vfsnr_vfsfm_fs42 (ID: 475)
add-features-to-set 475 --features 101 103 106

# Feature Set 452/560: cuhslp_vfsnr_cfsnr_fs42 (ID: 476)
add-features-to-set 476 --features 101 103 107

# Feature Set 453/560: cuhslp_vfsnr_cfpsd_fs42 (ID: 477)
add-features-to-set 477 --features 101 103 108

# Feature Set 454/560: cuhslp_vfsnr_cfslp_fs42 (ID: 478)
add-features-to-set 478 --features 101 103 109

# Feature Set 455/560: cuhslp_vfsnr_cfsfm_fs42 (ID: 479)
add-features-to-set 479 --features 101 103 110

# Feature Set 456/560: cuhslp_vfpsd_vfslp_fs42 (ID: 480)
add-features-to-set 480 --features 101 104 105

# Feature Set 457/560: cuhslp_vfpsd_vfsfm_fs42 (ID: 481)
add-features-to-set 481 --features 101 104 106

# Feature Set 458/560: cuhslp_vfpsd_cfsnr_fs42 (ID: 482)
add-features-to-set 482 --features 101 104 107

# Feature Set 459/560: cuhslp_vfpsd_cfpsd_fs42 (ID: 483)
add-features-to-set 483 --features 101 104 108

# Feature Set 460/560: cuhslp_vfpsd_cfslp_fs42 (ID: 484)
add-features-to-set 484 --features 101 104 109

# Feature Set 461/560: cuhslp_vfpsd_cfsfm_fs42 (ID: 485)
add-features-to-set 485 --features 101 104 110

# Feature Set 462/560: cuhslp_vfslp_vfsfm_fs42 (ID: 486)
add-features-to-set 486 --features 101 105 106

# Feature Set 463/560: cuhslp_vfslp_cfsnr_fs42 (ID: 487)
add-features-to-set 487 --features 101 105 107

# Feature Set 464/560: cuhslp_vfslp_cfpsd_fs42 (ID: 488)
add-features-to-set 488 --features 101 105 108

# Feature Set 465/560: cuhslp_vfslp_cfslp_fs42 (ID: 489)
add-features-to-set 489 --features 101 105 109

# Feature Set 466/560: cuhslp_vfslp_cfsfm_fs42 (ID: 490)
add-features-to-set 490 --features 101 105 110

# Feature Set 467/560: cuhslp_vfsfm_cfsnr_fs42 (ID: 491)
add-features-to-set 491 --features 101 106 107

# Feature Set 468/560: cuhslp_vfsfm_cfpsd_fs42 (ID: 492)
add-features-to-set 492 --features 101 106 108

# Feature Set 469/560: cuhslp_vfsfm_cfslp_fs42 (ID: 493)
add-features-to-set 493 --features 101 106 109

# Feature Set 470/560: cuhslp_vfsfm_cfsfm_fs42 (ID: 494)
add-features-to-set 494 --features 101 106 110

# Feature Set 471/560: cuhslp_cfsnr_cfpsd_fs42 (ID: 495)
add-features-to-set 495 --features 101 107 108

# Feature Set 472/560: cuhslp_cfsnr_cfslp_fs42 (ID: 496)
add-features-to-set 496 --features 101 107 109

# Feature Set 473/560: cuhslp_cfsnr_cfsfm_fs42 (ID: 497)
add-features-to-set 497 --features 101 107 110

# Feature Set 474/560: cuhslp_cfpsd_cfslp_fs42 (ID: 498)
add-features-to-set 498 --features 101 108 109

# Feature Set 475/560: cuhslp_cfpsd_cfsfm_fs42 (ID: 499)
add-features-to-set 499 --features 101 108 110

# Feature Set 476/560: cuhslp_cfslp_cfsfm_fs42 (ID: 500)
add-features-to-set 500 --features 101 109 110

# Feature Set 477/560: cuhsfm_vfsnr_vfpsd_fs42 (ID: 501)
add-features-to-set 501 --features 102 103 104

# Feature Set 478/560: cuhsfm_vfsnr_vfslp_fs42 (ID: 502)
add-features-to-set 502 --features 102 103 105

# Feature Set 479/560: cuhsfm_vfsnr_vfsfm_fs42 (ID: 503)
add-features-to-set 503 --features 102 103 106

# Feature Set 480/560: cuhsfm_vfsnr_cfsnr_fs42 (ID: 504)
add-features-to-set 504 --features 102 103 107

# Feature Set 481/560: cuhsfm_vfsnr_cfpsd_fs42 (ID: 505)
add-features-to-set 505 --features 102 103 108

# Feature Set 482/560: cuhsfm_vfsnr_cfslp_fs42 (ID: 506)
add-features-to-set 506 --features 102 103 109

# Feature Set 483/560: cuhsfm_vfsnr_cfsfm_fs42 (ID: 507)
add-features-to-set 507 --features 102 103 110

# Feature Set 484/560: cuhsfm_vfpsd_vfslp_fs42 (ID: 508)
add-features-to-set 508 --features 102 104 105

# Feature Set 485/560: cuhsfm_vfpsd_vfsfm_fs42 (ID: 509)
add-features-to-set 509 --features 102 104 106

# Feature Set 486/560: cuhsfm_vfpsd_cfsnr_fs42 (ID: 510)
add-features-to-set 510 --features 102 104 107

# Feature Set 487/560: cuhsfm_vfpsd_cfpsd_fs42 (ID: 511)
add-features-to-set 511 --features 102 104 108

# Feature Set 488/560: cuhsfm_vfpsd_cfslp_fs42 (ID: 512)
add-features-to-set 512 --features 102 104 109

# Feature Set 489/560: cuhsfm_vfpsd_cfsfm_fs42 (ID: 513)
add-features-to-set 513 --features 102 104 110

# Feature Set 490/560: cuhsfm_vfslp_vfsfm_fs42 (ID: 514)
add-features-to-set 514 --features 102 105 106

# Feature Set 491/560: cuhsfm_vfslp_cfsnr_fs42 (ID: 515)
add-features-to-set 515 --features 102 105 107

# Feature Set 492/560: cuhsfm_vfslp_cfpsd_fs42 (ID: 516)
add-features-to-set 516 --features 102 105 108

# Feature Set 493/560: cuhsfm_vfslp_cfslp_fs42 (ID: 517)
add-features-to-set 517 --features 102 105 109

# Feature Set 494/560: cuhsfm_vfslp_cfsfm_fs42 (ID: 518)
add-features-to-set 518 --features 102 105 110

# Feature Set 495/560: cuhsfm_vfsfm_cfsnr_fs42 (ID: 519)
add-features-to-set 519 --features 102 106 107

# Feature Set 496/560: cuhsfm_vfsfm_cfpsd_fs42 (ID: 520)
add-features-to-set 520 --features 102 106 108

# Feature Set 497/560: cuhsfm_vfsfm_cfslp_fs42 (ID: 521)
add-features-to-set 521 --features 102 106 109

# Feature Set 498/560: cuhsfm_vfsfm_cfsfm_fs42 (ID: 522)
add-features-to-set 522 --features 102 106 110

# Feature Set 499/560: cuhsfm_cfsnr_cfpsd_fs42 (ID: 523)
add-features-to-set 523 --features 102 107 108

# Feature Set 500/560: cuhsfm_cfsnr_cfslp_fs42 (ID: 524)
add-features-to-set 524 --features 102 107 109

# Progress: 500/560 feature sets fixed (89%)

# Feature Set 501/560: cuhsfm_cfsnr_cfsfm_fs42 (ID: 525)
add-features-to-set 525 --features 102 107 110

# Feature Set 502/560: cuhsfm_cfpsd_cfslp_fs42 (ID: 526)
add-features-to-set 526 --features 102 108 109

# Feature Set 503/560: cuhsfm_cfpsd_cfsfm_fs42 (ID: 527)
add-features-to-set 527 --features 102 108 110

# Feature Set 504/560: cuhsfm_cfslp_cfsfm_fs42 (ID: 528)
add-features-to-set 528 --features 102 109 110

# Feature Set 505/560: vfsnr_vfpsd_vfslp_fs42 (ID: 529)
add-features-to-set 529 --features 103 104 105

# Feature Set 506/560: vfsnr_vfpsd_vfsfm_fs42 (ID: 530)
add-features-to-set 530 --features 103 104 106

# Feature Set 507/560: vfsnr_vfpsd_cfsnr_fs42 (ID: 531)
add-features-to-set 531 --features 103 104 107

# Feature Set 508/560: vfsnr_vfpsd_cfpsd_fs42 (ID: 532)
add-features-to-set 532 --features 103 104 108

# Feature Set 509/560: vfsnr_vfpsd_cfslp_fs42 (ID: 533)
add-features-to-set 533 --features 103 104 109

# Feature Set 510/560: vfsnr_vfpsd_cfsfm_fs42 (ID: 534)
add-features-to-set 534 --features 103 104 110

# Feature Set 511/560: vfsnr_vfslp_vfsfm_fs42 (ID: 535)
add-features-to-set 535 --features 103 105 106

# Feature Set 512/560: vfsnr_vfslp_cfsnr_fs42 (ID: 536)
add-features-to-set 536 --features 103 105 107

# Feature Set 513/560: vfsnr_vfslp_cfpsd_fs42 (ID: 537)
add-features-to-set 537 --features 103 105 108

# Feature Set 514/560: vfsnr_vfslp_cfslp_fs42 (ID: 538)
add-features-to-set 538 --features 103 105 109

# Feature Set 515/560: vfsnr_vfslp_cfsfm_fs42 (ID: 539)
add-features-to-set 539 --features 103 105 110

# Feature Set 516/560: vfsnr_vfsfm_cfsnr_fs42 (ID: 540)
add-features-to-set 540 --features 103 106 107

# Feature Set 517/560: vfsnr_vfsfm_cfpsd_fs42 (ID: 541)
add-features-to-set 541 --features 103 106 108

# Feature Set 518/560: vfsnr_vfsfm_cfslp_fs42 (ID: 542)
add-features-to-set 542 --features 103 106 109

# Feature Set 519/560: vfsnr_vfsfm_cfsfm_fs42 (ID: 543)
add-features-to-set 543 --features 103 106 110

# Feature Set 520/560: vfsnr_cfsnr_cfpsd_fs42 (ID: 544)
add-features-to-set 544 --features 103 107 108

# Feature Set 521/560: vfsnr_cfsnr_cfslp_fs42 (ID: 545)
add-features-to-set 545 --features 103 107 109

# Feature Set 522/560: vfsnr_cfsnr_cfsfm_fs42 (ID: 546)
add-features-to-set 546 --features 103 107 110

# Feature Set 523/560: vfsnr_cfpsd_cfslp_fs42 (ID: 547)
add-features-to-set 547 --features 103 108 109

# Feature Set 524/560: vfsnr_cfpsd_cfsfm_fs42 (ID: 548)
add-features-to-set 548 --features 103 108 110

# Feature Set 525/560: vfsnr_cfslp_cfsfm_fs42 (ID: 549)
add-features-to-set 549 --features 103 109 110

# Feature Set 526/560: vfpsd_vfslp_vfsfm_fs42 (ID: 550)
add-features-to-set 550 --features 104 105 106

# Feature Set 527/560: vfpsd_vfslp_cfsnr_fs42 (ID: 551)
add-features-to-set 551 --features 104 105 107

# Feature Set 528/560: vfpsd_vfslp_cfpsd_fs42 (ID: 552)
add-features-to-set 552 --features 104 105 108

# Feature Set 529/560: vfpsd_vfslp_cfslp_fs42 (ID: 553)
add-features-to-set 553 --features 104 105 109

# Feature Set 530/560: vfpsd_vfslp_cfsfm_fs42 (ID: 554)
add-features-to-set 554 --features 104 105 110

# Feature Set 531/560: vfpsd_vfsfm_cfsnr_fs42 (ID: 555)
add-features-to-set 555 --features 104 106 107

# Feature Set 532/560: vfpsd_vfsfm_cfpsd_fs42 (ID: 556)
add-features-to-set 556 --features 104 106 108

# Feature Set 533/560: vfpsd_vfsfm_cfslp_fs42 (ID: 557)
add-features-to-set 557 --features 104 106 109

# Feature Set 534/560: vfpsd_vfsfm_cfsfm_fs42 (ID: 558)
add-features-to-set 558 --features 104 106 110

# Feature Set 535/560: vfpsd_cfsnr_cfpsd_fs42 (ID: 559)
add-features-to-set 559 --features 104 107 108

# Feature Set 536/560: vfpsd_cfsnr_cfslp_fs42 (ID: 560)
add-features-to-set 560 --features 104 107 109

# Feature Set 537/560: vfpsd_cfsnr_cfsfm_fs42 (ID: 561)
add-features-to-set 561 --features 104 107 110

# Feature Set 538/560: vfpsd_cfpsd_cfslp_fs42 (ID: 562)
add-features-to-set 562 --features 104 108 109

# Feature Set 539/560: vfpsd_cfpsd_cfsfm_fs42 (ID: 563)
add-features-to-set 563 --features 104 108 110

# Feature Set 540/560: vfpsd_cfslp_cfsfm_fs42 (ID: 564)
add-features-to-set 564 --features 104 109 110

# Feature Set 541/560: vfslp_vfsfm_cfsnr_fs42 (ID: 565)
add-features-to-set 565 --features 105 106 107


# Summary:
# - Empty feature sets found: 560
# - Commands generated: 560
# Feature Set 542/560: vfslp_vfsfm_cfpsd_fs42 (ID: 566)
add-features-to-set 566 --features 105 106 108

# Feature Set 543/560: vfslp_vfsfm_cfslp_fs42 (ID: 567)
add-features-to-set 567 --features 105 106 109

# Feature Set 544/560: vfslp_vfsfm_cfsfm_fs42 (ID: 568)
add-features-to-set 568 --features 105 106 110

# Feature Set 545/560: vfslp_cfsnr_cfpsd_fs42 (ID: 569)
add-features-to-set 569 --features 105 107 108

# Feature Set 546/560: vfslp_cfsnr_cfslp_fs42 (ID: 570)
add-features-to-set 570 --features 105 107 109

# Feature Set 547/560: vfslp_cfsnr_cfsfm_fs42 (ID: 571)
add-features-to-set 571 --features 105 107 110

# Feature Set 548/560: vfslp_cfpsd_cfslp_fs42 (ID: 572)
add-features-to-set 572 --features 105 108 109

# Feature Set 549/560: vfslp_cfpsd_cfsfm_fs42 (ID: 573)
add-features-to-set 573 --features 105 108 110

# Feature Set 550/560: vfslp_cfslp_cfsfm_fs42 (ID: 574)
add-features-to-set 574 --features 105 109 110

# Progress: 550/560 feature sets fixed (98%)

# Feature Set 551/560: vfsfm_cfsnr_cfpsd_fs42 (ID: 575)
add-features-to-set 575 --features 106 107 108

# Feature Set 552/560: vfsfm_cfsnr_cfslp_fs42 (ID: 576)
add-features-to-set 576 --features 106 107 109

# Feature Set 553/560: vfsfm_cfsnr_cfsfm_fs42 (ID: 577)
add-features-to-set 577 --features 106 107 110

# Feature Set 554/560: vfsfm_cfpsd_cfslp_fs42 (ID: 578)
add-features-to-set 578 --features 106 108 109

# Feature Set 555/560: vfsfm_cfpsd_cfsfm_fs42 (ID: 579)
add-features-to-set 579 --features 106 108 110

# Feature Set 556/560: vfsfm_cfslp_cfsfm_fs42 (ID: 580)
add-features-to-set 580 --features 106 109 110

# Feature Set 557/560: cfsnr_cfpsd_cfslp_fs42 (ID: 581)
add-features-to-set 581 --features 107 108 109

# Feature Set 558/560: cfsnr_cfpsd_cfsfm_fs42 (ID: 582)
add-features-to-set 582 --features 107 108 110

# Feature Set 559/560: cfsnr_cfslp_cfsfm_fs42 (ID: 583)
add-features-to-set 583 --features 107 109 110

# Feature Set 560/560: cfpsd_cfslp_cfsfm_fs42 (ID: 584)
add-features-to-set 584 --features 108 109 110

# ============================================================================
# Fix Complete
# ============================================================================
# Total: 560 feature sets fixed

# Verify all sets have 3 features:
# (SQL query to check feature counts)

