#!/usr/bin/env python3
"""
Filename: fix_add_features_comma_separated.py
Author(s): Kristophor Jensen
Date Created: 20251104_000000
Date Revised: 20251104_000000
File version: 1.0.0.2
Description: Fix feature sets using comma-separated format

Based on testing, the command likely needs:
  add-features-to-set <id> --features <id1>,<id2>,<id3>
OR we need to add features one at a time.

This script generates commands to add remaining features (2nd and 3rd).
"""

import psycopg2
import sys

# Configuration
DB_HOST = 'localhost'
DB_NAME = 'arc_detection'
DB_USER = 'kjensen'
CATEGORY = 'exp42_separability'

# Feature name to ID mapping
FEATURE_MAP = {
    'vuhsnr': 95, 'vuhpsd': 96, 'vuhslp': 97, 'vuhsfm': 98,
    'cuhsnr': 99, 'cuhpsd': 100, 'cuhslp': 101, 'cuhsfm': 102,
    'vfsnr': 103, 'vfpsd': 104, 'vfslp': 105, 'vfsfm': 106,
    'cfsnr': 107, 'cfpsd': 108, 'cfslp': 109, 'cfsfm': 110,
}

def parse_feature_ids_from_name(fs_name):
    """Extract feature IDs from feature set name."""
    name = fs_name.replace('_fs42', '')
    parts = name.split('_')
    feature_ids = []
    for part in parts:
        if part in FEATURE_MAP:
            feature_ids.append(FEATURE_MAP[part])
    return sorted(feature_ids)

def main():
    """Query database and generate fix commands."""
    try:
        conn = psycopg2.connect(host=DB_HOST, database=DB_NAME, user=DB_USER)
        cursor = conn.cursor()
    except Exception as e:
        print(f"ERROR: Database connection failed: {e}", file=sys.stderr)
        sys.exit(1)

    # Get all feature sets with their current features
    try:
        cursor.execute("""
            SELECT fs.feature_set_id, fs.feature_set_name, array_agg(f.feature_id ORDER BY f.feature_id) as current_features
            FROM ml_feature_sets_lut fs
            LEFT JOIN ml_feature_set_features f ON fs.feature_set_id = f.feature_set_id
            WHERE fs.category = %s
            GROUP BY fs.feature_set_id, fs.feature_set_name
            ORDER BY fs.feature_set_id
        """, (CATEGORY,))

        all_sets = cursor.fetchall()
    except Exception as e:
        print(f"ERROR: Database query failed: {e}", file=sys.stderr)
        sys.exit(1)
    finally:
        cursor.close()
        conn.close()

    print("# Fix Script: Add Missing Features (Comma-Separated)")
    print(f"# Generated by: fix_add_features_comma_separated.py v1.0.0.2")
    print()
    print("# ============================================================================")
    print("# Add Missing Features to Feature Sets")
    print("# ============================================================================")
    print()

    fixed_count = 0
    for fs_id, fs_name, current_features in all_sets:
        # Determine what features should be in this set
        expected_features = parse_feature_ids_from_name(fs_name)

        # Filter out None from current_features (happens with LEFT JOIN on empty sets)
        if current_features and current_features[0] is not None:
            current = set(current_features)
        else:
            current = set()

        # Find missing features
        missing = sorted(set(expected_features) - current)

        if missing:
            fixed_count += 1
            feature_list = ",".join(str(fid) for fid in missing)
            print(f"# Feature Set {fs_id}: {fs_name}")
            print(f"#   Current: {sorted(current)}")
            print(f"#   Expected: {expected_features}")
            print(f"#   Missing: {missing}")
            print(f"add-features-to-set {fs_id} --features {feature_list}")
            print()

            if fixed_count % 50 == 0:
                print(f"# Progress: {fixed_count} feature sets fixed")
                print()

    print("# ============================================================================")
    print("# Fix Complete")
    print("# ============================================================================")
    print(f"# Total: {fixed_count} feature sets fixed")
    print()

    print(f"\n# Summary:", file=sys.stderr)
    print(f"# - Feature sets needing fixes: {fixed_count}", file=sys.stderr)
    print(f"# - Total feature sets: {len(all_sets)}", file=sys.stderr)

if __name__ == "__main__":
    main()
