#!/usr/bin/env python3
"""
Filename: generate_exp42_feature_sets.py
Author(s): Kristophor Jensen
Date Created: 20251104_000000
Date Revised: 20251104_000000
File version: 1.0.0.1
Description: Generate all C(16,3)=560 feature set combinations for experiment 42

This script generates MLDP CLI commands to create all possible 3-feature
combinations from the 16 available PSD features (IDs 95-110).

Feature Pool (16 features):
- v_ultra_high: snr(95), mean_psd(96), slope(97), sfm(98)
- c_ultra_high: snr(99), mean_psd(100), slope(101), sfm(102)
- v_full: snr(103), mean_psd(104), slope(105), sfm(106)
- c_full: snr(107), mean_psd(108), slope(109), sfm(110)

Output: Shell script with 560 feature set creation commands
"""

from itertools import combinations
import sys

# Feature definitions
FEATURES = {
    95: 'v_ultra_high_snr',
    96: 'v_ultra_high_mean_psd',
    97: 'v_ultra_high_slope',
    98: 'v_ultra_high_sfm',
    99: 'c_ultra_high_snr',
    100: 'c_ultra_high_mean_psd',
    101: 'c_ultra_high_slope',
    102: 'c_ultra_high_sfm',
    103: 'v_full_snr',
    104: 'v_full_mean_psd',
    105: 'v_full_slope',
    106: 'v_full_sfm',
    107: 'c_full_snr',
    108: 'c_full_mean_psd',
    109: 'c_full_slope',
    110: 'c_full_sfm',
}

def generate_feature_set_name(feature_ids):
    """Generate a concise feature set name from feature IDs."""
    # Extract abbreviated names
    parts = []
    for fid in sorted(feature_ids):
        name = FEATURES[fid]
        # Parse: {channel}_{band}_{metric}
        channel = name[0]  # v or c
        if 'ultra' in name:
            band = 'uh'  # ultra_high
        else:
            band = 'f'   # full

        if 'snr' in name:
            metric = 'snr'
        elif 'mean_psd' in name:
            metric = 'psd'
        elif 'slope' in name:
            metric = 'slp'
        elif 'sfm' in name:
            metric = 'sfm'

        parts.append(f"{channel}{band}{metric}")

    return "_".join(parts) + "_fs42"

def generate_feature_set_description(feature_ids):
    """Generate description listing the 3 features."""
    names = [FEATURES[fid] for fid in sorted(feature_ids)]
    return f"Exp42 separability: {', '.join(names)}"

def main():
    """Generate all 560 feature set combinations."""

    feature_ids = list(FEATURES.keys())

    # Generate all C(16,3) = 560 combinations
    all_combinations = list(combinations(feature_ids, 3))

    print(f"# Generated {len(all_combinations)} feature set combinations")
    print(f"# Feature pool: {len(feature_ids)} features (IDs {min(feature_ids)}-{max(feature_ids)})")
    print(f"# Combinations: C({len(feature_ids)},3) = {len(all_combinations)}")
    print()
    print("# Experiment 42 Feature Set Generation Script")
    print("# Generated by: generate_exp42_feature_sets.py v1.0.0.1")
    print()
    print("# ============================================================================")
    print("# Create All 560 Feature Sets")
    print("# ============================================================================")
    print()

    for idx, combo in enumerate(all_combinations, 1):
        fs_name = generate_feature_set_name(combo)
        fs_desc = generate_feature_set_description(combo)
        feature_list = ",".join(str(fid) for fid in sorted(combo))

        print(f"# Feature Set {idx}/560: {fs_name}")
        print(f'create-global-feature-set --name "{fs_name}" --category "exp42_separability" --description "{fs_desc}"')
        print(f'add-features-to-set --set-name "{fs_name}" --features {feature_list}')
        print()

        # Add progress markers every 50 feature sets
        if idx % 50 == 0:
            print(f"# Progress: {idx}/560 feature sets created ({idx*100//560}%)")
            print()

    print("# ============================================================================")
    print("# Feature Set Generation Complete")
    print("# ============================================================================")
    print(f"# Total: {len(all_combinations)} feature sets created")
    print()

    # Generate verification command
    print("# Verify feature set count:")
    print("# show-all-feature-sets | grep exp42_separability | wc -l")
    print("# Expected: 560")
    print()

    # Write summary to stderr for user visibility
    print(f"\n# Summary written to stderr:", file=sys.stderr)
    print(f"# - Total feature sets: {len(all_combinations)}", file=sys.stderr)
    print(f"# - Feature pool size: {len(feature_ids)}", file=sys.stderr)
    print(f"# - Features per set: 3", file=sys.stderr)
    print(f"# - Category: exp42_separability", file=sys.stderr)
    print(f"# - Naming: <abbreviated_features>_fs42", file=sys.stderr)

if __name__ == "__main__":
    main()
