#!/usr/bin/env python3
"""
Filename: select_100_random_feature_sets.py
Author(s): Kristophor Jensen
Date Created: 20251104_000000
Date Revised: 20251104_000000
File version: 1.0.0.1
Description: Randomly select 100 feature sets from 560 exp42 feature sets

This script queries the database for all exp42_separability feature sets,
randomly selects 100, and generates MLDP CLI link commands.

Random Selection Strategy:
- Ensures unbiased sampling from full combinatorial space
- Reproducible with fixed random seed (42)
- Allows validation of complete feature set creation before selection

Usage:
  python3 select_100_random_feature_sets.py > link_100_feature_sets.sh

Then in MLDP CLI:
  source link_100_feature_sets.sh
"""

import psycopg2
import random
import sys

# Configuration
DB_HOST = 'localhost'
DB_NAME = 'arc_detection'
DB_USER = 'kjensen'
CATEGORY = 'exp42_separability'
SAMPLE_SIZE = 100
RANDOM_SEED = 42

def main():
    """Query database and randomly select 100 feature sets."""

    # Connect to database
    try:
        conn = psycopg2.connect(
            host=DB_HOST,
            database=DB_NAME,
            user=DB_USER
        )
        cursor = conn.cursor()
    except Exception as e:
        print(f"ERROR: Database connection failed: {e}", file=sys.stderr)
        sys.exit(1)

    # Query all exp42 feature sets
    try:
        cursor.execute("""
            SELECT feature_set_id, feature_set_name
            FROM ml_feature_sets_lut
            WHERE category = %s
            ORDER BY feature_set_id
        """, (CATEGORY,))

        all_feature_sets = cursor.fetchall()

    except Exception as e:
        print(f"ERROR: Database query failed: {e}", file=sys.stderr)
        sys.exit(1)
    finally:
        cursor.close()
        conn.close()

    # Validate count
    total_count = len(all_feature_sets)
    print(f"# Found {total_count} feature sets with category '{CATEGORY}'", file=sys.stderr)

    if total_count == 0:
        print("ERROR: No feature sets found. Run create_exp42_560_feature_sets.sh first.", file=sys.stderr)
        sys.exit(1)

    if total_count < SAMPLE_SIZE:
        print(f"WARNING: Only {total_count} feature sets available, selecting all.", file=sys.stderr)
        selected = all_feature_sets
    else:
        # Randomly select 100 with fixed seed for reproducibility
        random.seed(RANDOM_SEED)
        selected = random.sample(all_feature_sets, SAMPLE_SIZE)
        selected.sort(key=lambda x: x[0])  # Sort by ID for consistency

    # Generate output script
    print("# Random Selection of 100 Feature Sets for Experiment 42")
    print(f"# Generated by: select_100_random_feature_sets.py v1.0.0.1")
    print(f"# Random seed: {RANDOM_SEED}")
    print(f"# Total available: {total_count}")
    print(f"# Selected: {len(selected)}")
    print()
    print("# ============================================================================")
    print("# Link 100 Randomly Selected Feature Sets to Experiment 42")
    print("# ============================================================================")
    print()

    for idx, (fs_id, fs_name) in enumerate(selected, 1):
        print(f"# Feature Set {idx}/100: {fs_name} (ID: {fs_id})")
        print(f"link-feature-set {fs_id}")
        print()

        # Progress markers every 25
        if idx % 25 == 0:
            print(f"# Progress: {idx}/100 feature sets linked ({idx}%)")
            print()

    print("# ============================================================================")
    print("# Feature Set Linking Complete")
    print("# ============================================================================")
    print(f"# Total: {len(selected)} feature sets linked")
    print()

    # Verification command
    print("# Verify linked count:")
    print("# list-feature-sets | wc -l")
    print(f"# Expected: {len(selected)}")
    print()

    # Summary to stderr
    print(f"\n# Summary:", file=sys.stderr)
    print(f"# - Total feature sets in database: {total_count}", file=sys.stderr)
    print(f"# - Randomly selected: {len(selected)}", file=sys.stderr)
    print(f"# - Random seed: {RANDOM_SEED}", file=sys.stderr)
    print(f"# - Category: {CATEGORY}", file=sys.stderr)

    # List selected IDs to stderr for reference
    print(f"\n# Selected feature set IDs:", file=sys.stderr)
    id_list = [str(fs_id) for fs_id, _ in selected]
    print(f"# {', '.join(id_list)}", file=sys.stderr)

if __name__ == "__main__":
    main()
